// IMPORTED TYPES
import type { Song } from '$stores/playerStates';

const INTERVAL = 160;

export const flightOfTheBumblebee: Song = [
	{ notes: [], wait: 3000 },
	{ notes: [{ note: 'A2' }, { note: 'CS2' }, { note: 'E3' }, { note: 'A3' }] },
	{ notes: [{ note: 'A5' }], wait: INTERVAL },
	{ notes: [{ note: 'GS5' }], wait: INTERVAL },
	{ notes: [{ note: 'G5' }], wait: INTERVAL },
	{ notes: [{ note: 'FS5' }], wait: INTERVAL },
	{ notes: [{ note: 'G5' }], wait: INTERVAL },
	{ notes: [{ note: 'FS5' }], wait: INTERVAL },
	{ notes: [{ note: 'F5' }], wait: INTERVAL },
	{ notes: [{ note: 'E5' }], wait: INTERVAL },
	{ notes: [{ note: 'F5' }], wait: INTERVAL },
	{ notes: [{ note: 'E5' }], wait: INTERVAL },
	{ notes: [{ note: 'DS5' }], wait: INTERVAL },
	{ notes: [{ note: 'D5' }], wait: INTERVAL },
	{ notes: [{ note: 'CS5' }], wait: INTERVAL },
	{ notes: [{ note: 'C5' }], wait: INTERVAL },
	{ notes: [{ note: 'B4' }], wait: INTERVAL },
	{ notes: [{ note: 'A2' }, { note: 'E2' }, { note: 'G2' }, { note: 'A3' }] },
	{ notes: [{ note: 'AS4' }], wait: INTERVAL },
	{ notes: [{ note: 'A4' }], wait: INTERVAL },
	{ notes: [{ note: 'GS4' }], wait: INTERVAL },
	{ notes: [{ note: 'G4' }], wait: INTERVAL },
	{ notes: [{ note: 'FS4' }], wait: INTERVAL },
	{ notes: [{ note: 'G4' }], wait: INTERVAL },
	{ notes: [{ note: 'FS4' }], wait: INTERVAL },
	{ notes: [{ note: 'F4' }], wait: INTERVAL },
	{ notes: [{ note: 'E4' }], wait: INTERVAL },
	{ notes: [{ note: 'F4' }], wait: INTERVAL },
	{ notes: [{ note: 'E4' }], wait: INTERVAL },
	{ notes: [{ note: 'DS4' }], wait: INTERVAL },
	{ notes: [{ note: 'D4' }], wait: INTERVAL },
	{ notes: [{ note: 'CS4' }], wait: INTERVAL },
	{ notes: [{ note: 'C4' }], wait: INTERVAL },
	{ notes: [{ note: 'B3' }], wait: INTERVAL },
	{ notes: [{ note: 'AS3' }], wait: INTERVAL },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'E3' }], wait: INTERVAL },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'E3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'AS3' }], wait: INTERVAL },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'G2' }, { note: 'B2' }] },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'AS3' }], wait: INTERVAL },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'G2' }, { note: 'B2' }] },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'G2' }, { note: 'AS2' }] },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'E3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'CS3' }, { note: 'E2' }, { note: 'G2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'AS3' }], wait: INTERVAL },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'G2' }, { note: 'AS2' }] },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'E3' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'F2' }, { note: 'A2' }] },
	{ notes: [{ note: 'F3' }], wait: INTERVAL },
	{ notes: [{ note: 'FS3' }], wait: INTERVAL },
	{ notes: [{ note: 'G3' }], wait: INTERVAL },
	{ notes: [{ note: 'GS3' }], wait: INTERVAL },
	{ notes: [{ note: 'E3' }, { note: 'G2' }, { note: 'A2' }, { note: 'CS3' }] },
	{ notes: [{ note: 'A3' }], wait: INTERVAL },
	{ notes: [{ note: 'B3' }], wait: INTERVAL },
	{ notes: [{ note: 'C4' }], wait: INTERVAL },
	{ notes: [{ note: 'CS4' }], wait: INTERVAL },
	{ notes: [{ note: 'D2' }, { note: 'FS2' }, { note: 'C2' }] },
	{ notes: [{ note: 'D4' }], wait: INTERVAL },
];
